Repository eclipse-openj9/openj9, pull requests merged in 2018-02, with the labels that each got.

#1142 Implement -XjniAcc for all platforms
  runtime/compiler/trj9/env/j9method.cpp
  runtime/compiler/trj9/p/codegen/PPCJNILinkage.cpp
Labels: comp:jit

#1152 Add --no-check-certificate in getDependencies.pl
  test/TestConfig/scripts/tools/getDependencies.pl
Labels: comp:test, prio:high

#1147 Add Extensions for OpenJDK version to java -Xinternalversion
  runtime/util/openj9_version.c
Labels: comp:vm

#1158 Updates method handles to use newer java.lang.Class API
  jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
Labels: comp:vm, jdk11, project:valhalla

#1154 Add Export for JVM_VERSION
  test/TestConfig/makefile
  test/TestConfig/settings.mk
Labels: comp:test

#1118 Guard scratch memory initialization in a try/catch
  doc/compiler/aot/AOTClassChains.md
  doc/compiler/hcr/NextGenHCR.md
  doc/compiler/il/IL_FAQ.md
  doc/compiler/jprofiling/JProfiling.md
  doc/compiler/memory/MemoryManager.md
  doc/compiler/runtime/ExceptionHandling.md
  doc/compiler/runtime/MetadataReclamation.md
  doc/compiler/runtime/RuntimeAssumption.md
  runtime/compiler/trj9/control/CompilationThread.cpp
  runtime/compiler/trj9/control/CompilationThread.hpp
  runtime/compiler/trj9/control/HookedByTheJit.cpp
Labels: comp:jit

#1145 Scan RS concurrently
  runtime/gc_glue_java/ScavengerRootScanner.cpp
  runtime/gc_glue_java/ScavengerRootScanner.hpp
  runtime/gc_trace/TgcRootScanner.cpp
Labels: comp:gc, depends:omr

#1087 Add SCC modularity CML tests
  test/cmdLineTests/shareClassTests/SCCMLTests/SharedClassesModularityTests.xml
  test/cmdLineTests/shareClassTests/SCCMLTests/playlist.xml
Labels: comp:test

#1019 Remove java.logging requires from java.management
  jcl/j9modules.txt
  jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/LoggingMXBeanImpl.java
  jcl/src/java.management/share/classes/java/lang/management/DefaultPlatformMBeanProvider.java
  jcl/src/java.management/share/classes/module-info.java.extra
Labels: comp:vm

#1125 Remove java.version check in getProperty tests for jdk9+
  test/Java8andUp/build.xml
  test/Java8andUp/playlist.xml
  test/Java8andUp/src_90/org/openj9/test/java/lang/Test_System.java
Labels: comp:test

#1148 Prevent register spilling inside internal control flow
  runtime/compiler/trj9/p/codegen/J9TreeEvaluator.cpp
Labels: comp:jit

#1156 Add system properties for the OpenJDK extensions name and version
  runtime/vm/vmprops.c
Labels: comp:vm

#1162 Add generic test target
  test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
Labels: comp:test

#1169 Adding -Xdump:none to JCL_TEST
  test/Java8andUp/playlist.xml
  test/Java8andUp/testng.xml
Labels: comp:test

#1137 Enable final field reporter, check class init status before reporting
  runtime/oti/VMHelpers.hpp
Labels: comp:vm

#1176 Fix comment for getProcessCpuTimeImpl() to specify 1 ns units
  jcl/src/jdk.management/share/classes/com/ibm/lang/management/internal/ExtendedOperatingSystemMXBeanImpl.java
Labels: comp:doc

#1141 Enable OPENJ9_BUILD at makefile top level
  runtime/include/j9cfg.h.ftl
  runtime/include/vendor_version.h
  runtime/j9vm/module.xml
  runtime/jcl/cl_se10/module.xml
  runtime/jcl/cl_se7_basic/module.xml
  runtime/jcl/cl_se9/module.xml
  runtime/jcl/common/jclcinit.c
  runtime/makelib/targets.mk.ftl
  runtime/util/module.xml
  runtime/util/openj9_version.c
  runtime/util/openj9_version.h
  runtime/vm/jvminit.c
  runtime/vm/module.xml
  runtime/vm/vmprops.c
Labels: comp:vm

#1168 Clean Valhalla MVT and refactor to Valhalla L-World value types
  buildspecs/aix_ppc-64.spec
  buildspecs/aix_ppc-64_cmprssptrs.spec
  buildspecs/aix_ppc-64_codecov.spec
  buildspecs/aix_ppc.spec
  buildspecs/j9.flags
  buildspecs/linux_390-64.spec
  buildspecs/linux_390-64_cmprssptrs.spec
  buildspecs/linux_390-64_cmprssptrs_codecov.spec
  buildspecs/linux_390-64_codecov.spec
  buildspecs/linux_390.spec
  buildspecs/linux_arm.spec
  buildspecs/linux_arm_linaro.spec
  buildspecs/linux_ppc-64.spec
  buildspecs/linux_ppc-64_cmprssptrs.spec
  buildspecs/linux_ppc-64_cmprssptrs_le.spec
  buildspecs/linux_ppc-64_cmprssptrs_le_gcc.spec
  buildspecs/linux_ppc-64_le.spec
  buildspecs/linux_ppc-64_le_gcc.spec
  buildspecs/linux_ppc.spec
  buildspecs/linux_x86-64.spec
  buildspecs/linux_x86-64_cmprssptrs.spec
  buildspecs/linux_x86-64_cmprssptrs_cs.spec
  buildspecs/linux_x86-64_cmprssptrs_panama.spec
  buildspecs/linux_x86-64_codecov.spec
  buildspecs/linux_ztpf_390-64.spec
  buildspecs/linux_ztpf_390-64_cmprssptrs.spec
  buildspecs/osx_x86-64.spec
  buildspecs/win_x86-64.spec
  buildspecs/win_x86-64_cmprssptrs.spec
  buildspecs/win_x86.spec
  buildspecs/zos_390-64.spec
  buildspecs/zos_390-64_cmprssptrs.spec
  buildspecs/zos_390.spec
  runtime/bcutil/ClassFileOracle.cpp
  runtime/bcutil/ClassFileOracle.hpp
  runtime/bcutil/ROMClassBuilder.cpp
  runtime/oti/VM_MethodHandleKinds.h
  runtime/oti/bcnames.h
  runtime/oti/cfr.h
  runtime/oti/j9consts.h
  runtime/oti/j9nonbuilder.h
  runtime/util/bcnames.c
  runtime/util/bcsizes.c
  runtime/util/jbcmap.c
  runtime/util/pcstack.c
  runtime/util/sunbcrel.c
  runtime/util/vrfytbl.c
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/OutOfLineINL_jdk_experimental_value_ValueType.cpp
  runtime/vm/createramclass.cpp
  runtime/vm/resolvesupport.cpp
Labels: comp:vm, project:valhalla

#1177 Rename -XX:+StringCompression to -XX:+CompactStrings
  runtime/oti/jvminit.h
  runtime/vm/jvminit.c
Labels: comp:vm, jdk9

#1174 Cache actual size of non-persistent shared cache to a local variable
  runtime/shared_common/OSCachesysv.cpp
  runtime/shared_common/OSCachesysv.hpp
Labels: bug, comp:vm, perf

#1171 Add JCL repo SHA and tag, and OPENJ9_TAG to the javacore
  runtime/rasdump/javadump.cpp
Labels: comp:vm, depends:openjdk10, depends:openjdk8, depends:openjdk9

#1182 Check for arithmetic overflow in JNI string and array functions
  runtime/vm/jnimisc.cpp
Labels: bug, comp:vm

#1183 Add methods inherited from superinterfaces to iTables
  jcl/src/java.base/share/classes/java/lang/invoke/InterfaceHandle.java
  runtime/jcl/common/java_dyn_methodhandle.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/util_api.h
  runtime/oti/vm_api.h
  runtime/util/hshelp.c
  runtime/util/mthutil.c
  runtime/vm/MHInterpreter.cpp
  runtime/vm/createramclass.cpp
  runtime/vm/intfunc.c
  runtime/vm/jnicsup.cpp
  runtime/vm/resolvesupport.cpp
Labels: bug, comp:vm, footprint

#1186 Reorganize Jenkins files by type
  buildenv/jenkins/common/build
  buildenv/jenkins/common/pipeline-functions
  buildenv/jenkins/common/test
  buildenv/jenkins/jobs/builds/Build-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/builds/Build-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/builds/Build-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/builds/Build-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/infrastructure/copyrightCheck
  buildenv/jenkins/jobs/infrastructure/lineEndingsCheck
  buildenv/jenkins/jobs/infrastructure/omrMirror
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Extended-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Extended-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le
Labels: comp:build

#1189 Variable cm should be set after the NULL check of sharedClassConfig
  runtime/shared_common/shrinit.cpp
Labels: comp:vm

#1181 Temporarily remap defaultvalue and withfield opcodes
  runtime/bcutil/ClassFileOracle.cpp
Labels: comp:vm, project:valhalla

#1195 Variable cm should be set after the NULL check of sharedClassConfig
  runtime/shared_common/shrinit.cpp
Labels: comp:vm

#1184 Move get_sha to function
  buildenv/jenkins/common/pipeline-functions
Labels: bug, comp:build, prio:high

#875 String.regionMatches optimizations
  jcl/src/java.base/share/classes/java/lang/String.java
  runtime/compiler/trj9/codegen/J9RecognizedMethodsEnum.hpp
  runtime/compiler/trj9/env/j9method.cpp
  runtime/compiler/trj9/il/symbol/J9MethodSymbol.cpp
  runtime/compiler/trj9/optimizer/InlinerTempForJ9.cpp
Labels: comp:jit, comp:vm

#1173 Remove excludes for Windows tests that pass now
  test/VM_Test/j9vm.xml
  test/cmdLineTests/libpathTest/exclude.xml
  test/cmdLineTests/libpathTest/exclude_rtfchild.xml
Labels: comp:test

#1187 Update parallel setting none value
  test/Java8andUp/testng.xml
Labels: comp:test

#1197 Print total number of tests before test execution
  test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl
  test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl
  test/TestConfig/settings.mk
Labels: comp:test

#1211 Disable legacy system initialization code
  jcl/src/java.base/share/classes/java/lang/System.java
Labels: comp:vm

#1222 Remove useless #undef directives
  runtime/include/j9cfg.h.ftl
Labels: comp:vm

#1219 Remove dead code
  buildspecs/aix_ppc-64.spec
  buildspecs/aix_ppc-64_cmprssptrs.spec
  buildspecs/aix_ppc-64_codecov.spec
  buildspecs/aix_ppc.spec
  buildspecs/j9.flags
  buildspecs/linux_390-64.spec
  buildspecs/linux_390-64_cmprssptrs.spec
  buildspecs/linux_390-64_cmprssptrs_codecov.spec
  buildspecs/linux_390-64_codecov.spec
  buildspecs/linux_390.spec
  buildspecs/linux_arm.spec
  buildspecs/linux_arm_linaro.spec
  buildspecs/linux_ppc-64.spec
  buildspecs/linux_ppc-64_cmprssptrs.spec
  buildspecs/linux_ppc-64_cmprssptrs_le.spec
  buildspecs/linux_ppc-64_cmprssptrs_le_gcc.spec
  buildspecs/linux_ppc-64_le.spec
  buildspecs/linux_ppc-64_le_gcc.spec
  buildspecs/linux_ppc.spec
  buildspecs/linux_x86-64.spec
  buildspecs/linux_x86-64_cmprssptrs.spec
  buildspecs/linux_x86-64_cmprssptrs_cs.spec
  buildspecs/linux_x86-64_cmprssptrs_panama.spec
  buildspecs/linux_x86-64_codecov.spec
  buildspecs/linux_x86.spec
  buildspecs/linux_x86_codecov.spec
  buildspecs/linux_ztpf_390-64.spec
  buildspecs/linux_ztpf_390-64_cmprssptrs.spec
  buildspecs/osx_x86-64.spec
  buildspecs/win_x86-64.spec
  buildspecs/win_x86-64_cmprssptrs.spec
  buildspecs/win_x86.spec
  buildspecs/zos_390-64.spec
  buildspecs/zos_390-64_cmprssptrs.spec
  buildspecs/zos_390.spec
  runtime/oti/j9nonbuilder.h
Labels: comp:vm

#1199 Update release process to change tag and branch names
  doc/processes/release_process.md
Labels: comp:doc

#1215 Fix Valhalla value types opcode remap typos in ClassFileOracle.cpp
  runtime/bcutil/ClassFileOracle.cpp
Labels: comp:vm, project:valhalla

#1218 Fix warnings from tracegen
  runtime/vm/j9vm.tdf
Labels: comp:vm

#1231 Fix ddr plugin manager
  jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/Container.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/Entry.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/java/diagnostics/utils/plugins/impl/PluginManagerImpl.java
Labels: comp:vm

#1217 Remove remaining Valhalla MVT code
  buildspecs/j9.flags
  jcl/jpp_configuration.xml
  jcl/src/java.base/share/classes/java/lang/invoke/DefaultValueHandle.java
  jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
  jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
  jcl/src/java.base/share/classes/jdk/experimental/value/ValueType.java
  jcl/src/java.base/share/classes/jvm/internal/value/DeriveValueType.java
  jcl/src/java.base/share/classes/module-info.java.extra
  runtime/bcutil/ClassFileOracle.cpp
  runtime/bcutil/ClassFileOracle.hpp
  runtime/bcutil/ROMClassBuilder.cpp
  runtime/oti/VM_MethodHandleKinds.h
  runtime/oti/j9nonbuilder.h
  runtime/vm/MHInterpreter.cpp
  runtime/vm/OutOfLineINL.hpp
  runtime/vm/OutOfLineINL_jdk_experimental_value_ValueType.cpp
  runtime/vm/bindnatv.cpp
Labels: comp:vm, project:valhalla

#1216 Add ACC_VALUE_TYPE class access modifier for Valhalla L-World
  runtime/oti/cfr.h
  runtime/oti/j9nonbuilder.h
Labels: comp:vm, project:valhalla

#1226 Enable System.startSNMPAgent in OpenJ9 Java 8
  jcl/src/java.base/share/classes/java/lang/Thread.java
  runtime/jcl/uma/se8_exports.xml
  runtime/jcl/uma/se9_exports.xml
Labels: comp:vm, jdk8

#1223 Export access to DDR for b165+
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/ImageFactory.java
Labels: comp:vm

#1241 Improve javadoc for ImageFactory
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/ImageFactory.java
Labels: comp:doc, comp:vm

#1239 Remove unnecessary $(D) in -DRESJAR value for stackSizeInfoTest
  test/cmdLineTests/stackSizeInfoTest/playlist.xml
Labels: comp:test

#1230 Adjust DDR namespace annotations
  runtime/compiler/trj9/runtime/MethodMetaData.h
  runtime/gc_base/ScavengerForwardedHeader.hpp
  runtime/oti/j9nonbuilder.h
  runtime/oti/jlm.h
  runtime/oti/stackwalk.h
  sourcetools/j9constantpool/com/ibm/oti/VMCPTool/Main.java
Labels: comp:vm

#1208 Support 'all' test levels in PR builds
  buildenv/jenkins/README.md
Labels: comp:build, comp:doc

#1242 Don't report final field modification at jit compile time
  runtime/vm/resolvesupport.cpp
Labels: bug, comp:vm

#1221 Relocate DDR test code
  debugtools/DDR_VM/launch_configs/DTFJHeapSectionUnitTest.launch
  debugtools/DDR_VM/launch_configs/DTFJHeapUnitTest (with logging).launch
  debugtools/DDR_VM/launch_configs/DTFJHeapUnitTest.launch
  debugtools/DDR_VM/testsrc/com/ibm/j9ddr/tools/xml/DTFJHeapSectionUnitTest.java
  debugtools/DDR_VM/testsrc/com/ibm/j9ddr/tools/xml/DTFJHeapUnitTest.java
  debugtools/DDR_VM/testsrc/com/ibm/j9ddr/tools/xml/DTFJTest.java
  debugtools/DDR_VM/testsrc/com/ibm/j9ddr/tools/xml/XMLComparisonUnitTest.java
Labels: comp:test

#1191 Improve GC pause times by removing assumptions in one pass
  doc/compiler/runtime/RuntimeAssumption.md
  runtime/compiler/trj9/control/HookedByTheJit.cpp
  runtime/compiler/trj9/env/RuntimeAssumptionTable.hpp
  runtime/compiler/trj9/runtime/ClassUnloadAssumption.cpp
  runtime/compiler/trj9/runtime/HookHelpers.cpp
  runtime/compiler/trj9/runtime/HookHelpers.hpp
Labels: comp:jit

#1251 Fix failed target
  test/README.md
  test/TestConfig/makefile
  test/TestConfig/scripts/testKitGen/resultsSummary/resultsSum.pl
  test/TestConfig/settings.mk
Labels: comp:test

#1243 Delete unused tenant-related constants
  runtime/jit_vm/ctsupport.c
  runtime/oti/j9nonbuilder.h
  runtime/vm/resolvesupport.cpp
Labels: comp:vm

#1256 Add null check for j.l.security.AccessControlContext.context
  jcl/src/java.base/share/classes/java/security/AccessControlContext.java
  jcl/src/java.base/share/classes/java/security/AccessController.java
Labels: bug, comp:vm

#56 Take ownership of jdk.internal.misc.Unsafe
  jcl/src/java.base/share/classes/com/ibm/oti/util/ExternalMessages-MasterIndex.properties
  jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java
  jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
  runtime/jcl/common/jclcinit.c
  runtime/jcl/common/sun_misc_Unsafe.cpp
  runtime/jcl/uma/sun_misc_Unsafe_exports.xml
  runtime/oti/vmconstantpool.xml
Labels: comp:vm, depends:EclipseCQ, jdk9, perf

#1261 Fix comment in JNICriticalRegion.hpp
  runtime/gc_glue_java/JNICriticalRegion.hpp
Labels: comp:gc

#1172 Adopt Java 11 jdk.internal.reflect.Reflection.getCallerClass API
  runtime/buildtools.mk
  runtime/j9vm/vmi.c
  runtime/j9vm_jdk11/generated.h.ftl
  runtime/j9vm_jdk11/module.xml
  runtime/jcl/cl_se11/module.xml
  runtime/jcl/common/vm_scar.c
  runtime/oti/sunvmi_api.h
  runtime/oti/vmconstantpool.xml
  runtime/redirector/forwarders.ftl
  runtime/redirector/module.xml
  runtime/sunvmi/sunvmi.c
  runtime/sunvmi_jdk11/module.xml
  runtime/util/vmargs.c
  runtime/vm/vmprops.c
Labels: comp:vm, depends:openjdk11, jdk11

#1258 Change fastIdentityHashCode() to use unsigned int to long conversion
  jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
  runtime/compiler/trj9/codegen/J9RecognizedMethodsEnum.hpp
  runtime/compiler/trj9/env/j9method.cpp
  runtime/compiler/trj9/optimizer/InlinerTempForJ9.cpp
Labels: bug, comp:vm, userRaised

#1284 Add new objectFieldOffset for Java 10 and up
  jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
Labels: comp:vm, jdk10

#1228 JIT runtime helper for final field notification
  runtime/codert_vm/armnathelp.m4
  runtime/codert_vm/cnathelp.cpp
  runtime/codert_vm/pnathelp.m4
  runtime/codert_vm/xnathelp.m4
  runtime/codert_vm/znathelp.m4
  runtime/compiler/trj9/control/rossa.cpp
  runtime/oti/VMHelpers.hpp
  runtime/oti/j9nonbuilder.h
Labels: comp:vm

#1281 Fix cmdLineTester_test_0 test 12 error on windows
  test/TestConfig/settings.mk
  test/cmdLineTests/cmdlinetestertests/cmdlinetests.xml
  test/cmdLineTests/cmdlinetestertests/exclude.xml
  test/cmdLineTests/cmdlinetestertests/playlist.xml
  test/cmdLineTests/cmdlinetestertests/test12.xml
Labels: comp:test

#1259 Remove legacy DDR code
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/OptInfo.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/gc/GCHeapLinkedFreeHeader_V1.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/walkers/LocalVariableTableIterator.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RamClassWalker.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/RomClassWalker.java
Labels: comp:gc, comp:vm

#1286 Export JVM_GetCallerClass according to Java version & API
  runtime/j9vm/j9vmnatives.xml
  runtime/j9vm/module.xml
  runtime/j9vm_b150/module.xml
  runtime/j9vm_b156/module.xml
  runtime/j9vm_jdk11/module.xml
  runtime/redirector/module.xml
Labels: comp:vm

#1292 Heed @FrameIteratorSkip in Class, AccessController
  runtime/jcl/common/java_lang_Class.cpp
  runtime/oti/j9consts.h
  runtime/vm/swalk.c
Labels: comp:vm

#1293 Adjust DDR in preparation for use of OMR's ddrgen
  debugtools/DDR_VM/src/com/ibm/j9ddr/StructureTypeManager.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/corereaders/CoreReader.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/AlgorithmPicker.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/JITStackWalker.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackwalker/MethodMetaData.java
Labels: comp:vm

#1202 Reformat Jenkins files to use configuration settings
  buildenv/jenkins/common/build
  buildenv/jenkins/common/pipeline-functions
  buildenv/jenkins/common/test
  buildenv/jenkins/common/variables-functions
  buildenv/jenkins/jobs/builds/Build-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/builds/Build-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/builds/Build-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/builds/Build-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Compile-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Extended-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/pull-requests/PullRequest-Sanity-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Extended-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Extended-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK8-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK9-linux_390-64_cmprssptrs
  buildenv/jenkins/jobs/tests/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le
  buildenv/jenkins/variables/defaults.yml
Labels: comp:build

#1287 Update the Javadoc for com.ibm.oti.shared
  jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedAbstractHelperFactory.java
  jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassCacheInfo.java
Labels: comp:vm

#1295 Identify unsafe stubs in javadocs
  jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
  runtime/jcl/common/sun_misc_Unsafe.cpp
Labels: comp:doc

#1245 Move common ThreadMXBean testcase code to TestUtilities
  test/Java8andUp/src/org/openj9/test/java/lang/management/ThreadMXBean/NoBlock.java
  test/Java8andUp/src_80/org/openj9/test/java/lang/management/ThreadMXBean/ThreadMXBeanTestCase.java
  test/Java8andUp/src_90/org/openj9/test/java/lang/management/ThreadMXBean/ThreadMXBeanTestCase.java
  test/TestUtilities/src/org/openj9/test/java/lang/management/ThreadMXBean/ThreadMXBeanTestCaseCommon.java
Labels: comp:test

#1233 Refactor MM_ScavengerHotFieldStats to be dynamically allocated
  runtime/gc_vlhgc/CopyForwardScheme.cpp
Labels: comp:gc, depends:omr

#1299 Fix missing define
  runtime/jilgen/jilconsts.c
Labels: comp:vm

#924 Mention the preferred version of GCC on Windows
  buildenv/Build_Instructions_V9.md
Labels: comp:doc
