Repository eclipse-openj9/openj9, pull requests merged in 2022-10, with the labels that each got.

#16020 Fix J9VMInternals.getStackTrace() to return null for a null throwable
  runtime/jcl/common/java_lang_J9VMInternals.cpp
Labels: project:loom

#16025 Update VirtualThread test options/requirements
  test/functional/Java19andUp/playlist.xml
Labels: project:loom

#15916 AArch64 JIT changes for virtual thread support
  runtime/compiler/aarch64/codegen/ARM64JNILinkage.cpp
  runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Labels: comp:jit, arch:aarch64, project:loom

#15752 Z JIT Pinning Support
  runtime/compiler/z/codegen/J9TreeEvaluator.cpp
  runtime/compiler/z/codegen/S390PrivateLinkage.cpp
Labels: project:loom

#16024 Update Continuation.yield to use onPinned API
  jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
  test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
Labels: project:loom

#16038 Remove include X86Evaluator.hpp
  runtime/compiler/x/codegen/J9TreeEvaluator.cpp
Labels: comp:jit

#16017 Add missing relos in dumpRelocationHeaderData
  runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
  runtime/compiler/runtime/RelocationRecord.cpp
Labels: comp:jit, comp:jit:aot

#16033 Avoid compilation failures due to imprecision in memory availability readout
  runtime/compiler/control/CompilationThread.cpp
  runtime/compiler/control/J9Options.cpp
Labels: comp:jit

#15769 JIT Pinning support for JDK19 on Power
  runtime/compiler/p/codegen/J9TreeEvaluator.cpp
  runtime/compiler/p/codegen/PPCJNILinkage.cpp
Labels: project:loom

#16060 Add OpenJDK configure reference to build instructions
  doc/build-instructions/Build_Instructions_V11.md
  doc/build-instructions/Build_Instructions_V17.md
  doc/build-instructions/Build_Instructions_V18.md
  doc/build-instructions/Build_Instructions_V8.md
Labels: comp:doc

#16058 Doc: Update TOC to include the doc on IL Opcodes
  doc/compiler/README.md
Labels: comp:doc

#16067 Fix spelling of troubleshooting in the build instructions
  doc/build-instructions/Build_Instructions_V11.md
  doc/build-instructions/Build_Instructions_V17.md
  doc/build-instructions/Build_Instructions_V18.md
  doc/build-instructions/Build_Instructions_V8.md
Labels: comp:doc

#16071 Fix blocking object to be the correct object
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/builder/javacore/JavaRuntimeBuilder.java
Labels: comp:vm

#16065 Add information about the test and debug-image to build instructions
  doc/build-instructions/Build_Instructions_V11.md
  doc/build-instructions/Build_Instructions_V17.md
  doc/build-instructions/Build_Instructions_V18.md
  doc/build-instructions/Build_Instructions_V8.md
Labels: comp:doc

#16059 Fix small memory leak at JITServer
  runtime/compiler/control/JITServerCompilationThread.cpp
Labels: comp:jitserver

#16041 Add new method Class.isIdentity()
  jcl/src/java.base/share/classes/java/lang/Class.java
  runtime/oti/VMHelpers.hpp
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/FastJNI_java_lang_Class.cpp
  runtime/vm/bindnatv.cpp
  runtime/vm/romclasses.c
  test/functional/Valhalla/build.xml
  test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeTests.java
Labels: comp:vm, comp:test, project:valhalla

#16042 CRIU delayedLockingOperation for fast JNI notify/notifyAll
  runtime/vm/FastJNI_java_lang_Object.cpp
Labels: comp:vm, criu

#15926 X64 FFI upcall thunk generation
  runtime/vm/wa64/UpcallThunkGen.cpp
  runtime/vm/xa64/UpcallThunkGen.cpp
Labels: arch:x86, os:linux, os:macos, os:windows

#15854 Add Exception message to Xdump stack agent output
  runtime/nls/dump/j9dmp.nls
  runtime/rasdump/trigger.c
Labels: comp:vm

#16087 Fix Continuation collection issue
  runtime/gc_glue_java/ScavengerRootClearer.cpp
  runtime/gc_vlhgc/CopyForwardScheme.cpp
Labels: comp:gc, project:loom

#16093 Fix a typo
  runtime/gc_glue_java/ScavengerRootClearer.cpp
Labels: comp:gc

#16069 Enable Gencon/Balanced/OptAvgPause GC policy in testing
  test/functional/Java19andUp/playlist.xml
Labels: comp:test, comp:gc, project:loom

#16097 Include all ELF objects listed in FILE notes
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
Labels: comp:vm

#16104 macOS: Fix captureCommandLine()
  runtime/j9vm/jvm.c
Labels: comp:vm, os:macos

#16077 Fix parsing of Javacore stack traces
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/thread/IThreadTypes.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/thread/ThreadSectionParser.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/thread/ThreadTagParser.java
Labels: comp:vm

#16101 Fix check in JITServer AOT class chain compilation
  runtime/compiler/runtime/JITClientSession.cpp
Labels: comp:jitserver

#15960 Handle vector mask testAny, testAll and conversion opcodes in VectorAPIExpansion
  runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
  runtime/compiler/env/j9method.cpp
  runtime/compiler/optimizer/VectorAPIExpansion.cpp
  runtime/compiler/optimizer/VectorAPIExpansion.hpp
Labels: comp:jit, depends:omr

#16092 Update JDK version for Valhalla
  runtime/bcutil/cfreader.c
  test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeGenerator.java
Labels: comp:vm, comp:test, project:valhalla

#16062 Cache J9I2JState in J9VMContinuation during transition
  runtime/oti/j9nonbuilder.h
  runtime/vm/ContinuationHelpers.cpp
  runtime/vm/ContinuationHelpers.hpp
  test/functional/Java19andUp/playlist.xml
Labels: project:loom

#16014 Init jitTOC on ppc64
  runtime/vm/ContinuationHelpers.cpp
  runtime/vm/ContinuationHelpers.hpp
  test/functional/Java19andUp/playlist.xml
Labels: project:loom

#16118 Include libraries and symbolic links based on SONAMEs
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/corereaders/NewElfDump.java
Labels: comp:vm

#16122 Disallow nop guards for interface call sites
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
  runtime/compiler/optimizer/J9CallGraph.hpp
  runtime/compiler/optimizer/J9Inliner.cpp
Labels: comp:jit

#16123 (0.35) Disallow nop guards for interface call sites
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
  runtime/compiler/optimizer/J9CallGraph.hpp
  runtime/compiler/optimizer/J9Inliner.cpp
Labels: comp:jit

#16117 Updated 0.35 release notes tables
  doc/release-notes/0.35/0.35.md
Labels: comp:doc

#16135 Add stub unsafe methods
  jcl/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
Labels: comp:vm, project:valhalla

#16137 Avoid to cache scavenger too early in StandardAccessBarrier
  runtime/gc_base/modronapi.cpp
  runtime/gc_glue_java/ScavengerDelegate.cpp
  runtime/gc_modron_standard/StandardAccessBarrier.cpp
  runtime/gc_modron_standard/StandardAccessBarrier.hpp
Labels: comp:gc, project:loom

#16139 Remove com.ibm.oti.vm.VM.PACKED_SUPPORT_ENABLED
  jcl/src/java.base/share/classes/com/ibm/oti/vm/VM.java
Labels: comp:vm

#16154 Remove uses of unsupported freetype configure options
  doc/build-instructions/Build_Instructions_V11.md
  doc/build-instructions/Build_Instructions_V17.md
  doc/build-instructions/Build_Instructions_V18.md
  doc/build-instructions/Build_Instructions_V8.md
Labels: comp:doc

#16143 JDK19+ implements carrier thread local Access APIs
  jcl/src/java.base/share/classes/java/lang/Access.java
Labels: comp:vm, jdk19

#16163 Fix JDKNext duplicated Access API definitions
  jcl/src/java.base/share/classes/java/lang/Access.java
Labels: comp:vm, jdk20

#15949 Add JITServer AOT cache persistence
  runtime/compiler/runtime/JITServerAOTCache.cpp
  runtime/compiler/runtime/JITServerAOTCache.hpp
  runtime/compiler/runtime/JITServerAOTSerializationRecords.hpp
Labels: comp:jitserver

#15956 Patch MXBean to support virtual threads
  runtime/jcl/common/mgmtthread.c
  runtime/util/thrinfo.c
Labels: project:loom

#16158 Handle mounted CarrierThread in Thread.getStackTrace
  runtime/jcl/common/getstacktrace.c
  runtime/jcl/common/thread.cpp
  runtime/oti/jclprots.h
Labels: project:loom

#16180 Use exclusive access correctly in getThreads
  runtime/jcl/common/thread.cpp
Labels: comp:vm

#16181 Get threadObject from targetThread in mgmtthread.c::getThreadInfo
  runtime/jcl/common/mgmtthread.c
Labels: comp:vm

#16170 Get defined argument from the bottom of the vmInitArgs->options array
  runtime/jcl/common/system.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/util_api.h
  runtime/oti/vm_api.h
  runtime/util/defarg.c
  runtime/util/util.tdf
  runtime/vm/vmbootlib.c
  test/functional/cmdLineTests/SystemPropertiesTest/playlist.xml
  test/functional/cmdLineTests/SystemPropertiesTest/src/SysPropRepeatDefinesTest.java
  test/functional/cmdLineTests/SystemPropertiesTest/sysproprepeatdefinestest.xml
Labels: comp:vm, comp:test

#16195 Read thread count under lock in getThreads
  runtime/jcl/common/thread.cpp
Labels: comp:vm

#16196 Missing bounds check for offsetByCodePoints
  jcl/src/java.base/share/classes/java/lang/String.java
  jcl/src/java.base/share/classes/java/lang/StringBuffer.java
  jcl/src/java.base/share/classes/java/lang/StringBuilder.java
  test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_String.java
  test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuffer.java
  test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuilder.java
Labels: comp:vm

#16201 Remove some uses of TR::comp()
  runtime/compiler/codegen/J9CodeGenerator.cpp
  runtime/compiler/env/VMJ9.cpp
  runtime/compiler/il/J9Node.cpp
  runtime/compiler/il/J9Node.hpp
  runtime/compiler/ilgen/Walker.cpp
  runtime/compiler/optimizer/EscapeAnalysis.cpp
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
  runtime/compiler/optimizer/SequentialStoreSimplifier.cpp
  runtime/compiler/optimizer/UnsafeFastPath.cpp
  runtime/compiler/optimizer/VarHandleTransformer.cpp
  runtime/compiler/z/codegen/J9BCDTreeEvaluator.cpp
  runtime/compiler/z/codegen/J9CodeGenerator.cpp
  runtime/compiler/z/codegen/S390Register.cpp
Labels: comp:jit

#16197 Fix assertion error in Unsafe.isFlattened
  runtime/vm/BytecodeInterpreter.hpp
  test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTestClasses.java
  test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java
Labels: comp:vm, project:valhalla

#16220 CRIU avoid unnecessary park() when a balancing unpark() occurred
  runtime/vm/threadhelp.cpp
Labels: comp:vm, criu

#16108 [JDK19]Update VaList test cases for Linux/s390x
  test/functional/Java19andUp/playlist.xml
  test/functional/Java19andUp/src/org/openj9/test/jep424/valist/ApiTests.java
  test/functional/Java19andUp/src/org/openj9/test/jep424/valist/DowncallTests.java
  test/functional/Java19andUp/src/org/openj9/test/jep424/valist/UpcallTests.java
  test/functional/Java19andUp/src/org/openj9/test/jep424/valist/VaListUpcallMethodHandles.java
Labels: project:panama

#16119 Fix EA so that it does not assume monExit will always execute an lwsync
  runtime/compiler/optimizer/EscapeAnalysis.cpp
  runtime/compiler/optimizer/EscapeAnalysis.hpp
  runtime/compiler/p/codegen/J9TreeEvaluator.cpp
Labels: comp:jit, depends:omr:breaking

#16091 CRIU nanoTimeMonotonicClockDelta calculation adjusted
  runtime/criusupport/criusupport.cpp
  runtime/criusupport/j9criu.tdf
  runtime/vm/CRIUHelpers.cpp
Labels: comp:vm, criu

#16166 Give a name to the default JITServer AOT cache
  runtime/compiler/env/J9PersistentInfo.hpp
Labels: comp:jitserver

#16231 Fix bool constant values
  runtime/vm/threadhelp.cpp
Labels: comp:vm

#16200 Clean up x86 monent/monexit inline sequences
  runtime/compiler/codegen/J9TreeEvaluator.cpp
  runtime/compiler/codegen/J9TreeEvaluator.hpp
  runtime/compiler/x/codegen/J9TreeEvaluator.cpp
  runtime/compiler/x/codegen/J9TreeEvaluator.hpp
Labels: comp:jit

#15922 Use primitiveObjectHashCode function when hashing value types
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/HashCodeCommand.java
  jcl/src/java.base/share/classes/java/lang/Class.java
  jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
  jcl/src/java.base/share/classes/java/lang/Object.java
  runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp
  runtime/oti/VMHelpers.hpp
  runtime/oti/j9nonbuilder.h
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/bindnatv.cpp
Labels: comp:vm, project:valhalla
