Repository eclipse-openj9/openj9, pull requests merged in 2022-09, with the labels that each got.

#15753 Virtual threads support for jvmtiGetFrameCount
  runtime/jvmti/j9jvmti.tdf
  runtime/jvmti/jvmtiStackFrame.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/vmconstantpool.xml
  runtime/vm/intfunc.c
Labels: comp:vm, project:loom, jdk19

#15815 Correct signal names from java dumps
  debugtools/DDR_VM/src/com/ibm/j9ddr/view/dtfj/image/J9DDRImageProcess.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/j9/SignalName.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/image/javacore/JCImageProcess.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/platform/PlatformPatternMatchers.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/platform/PlatformSectionParser.java
  jcl/src/openj9.dtfj/share/classes/com/ibm/dtfj/javacore/parser/j9/section/platform/PlatformTagParser.java
Labels: comp:vm

#15817 zTPF: Update gc glue configure to use tpf-as
  runtime/gc_glue_java/configure_includes/configure_linux_ztpf_390.mk
Labels: comp:build

#15754 Skip method test bound check when guard node is flagged in-bounds
  runtime/compiler/codegen/J9CodeGenerator.cpp
Labels: comp:jit

#15603 Loom: GC Scan Continuation Object
  runtime/compiler/env/J9ClassEnv.cpp
  runtime/compiler/env/VMJ9.cpp
  runtime/compiler/env/VMJ9.h
  runtime/compiler/env/VMJ9Server.cpp
  runtime/compiler/env/VMJ9Server.hpp
  runtime/compiler/net/CommunicationStream.hpp
  runtime/gc_api/HeapIteratorAPI.cpp
  runtime/gc_base/ObjectAccessBarrier.cpp
  runtime/gc_base/ObjectAccessBarrier.hpp
  runtime/gc_base/ReferenceChainWalker.cpp
  runtime/gc_glue_java/CMakeLists.txt
  runtime/gc_glue_java/CompactDelegate.cpp
  runtime/gc_glue_java/CompactSchemeFixupObject.cpp
  runtime/gc_glue_java/CompactSchemeFixupObject.hpp
  runtime/gc_glue_java/HeapWalkerDelegate.cpp
  runtime/gc_glue_java/HeapWalkerDelegate.hpp
  runtime/gc_glue_java/MarkingDelegate.cpp
  runtime/gc_glue_java/MarkingDelegate.hpp
  runtime/gc_glue_java/MetronomeDelegate.cpp
  runtime/gc_glue_java/MetronomeDelegate.hpp
  runtime/gc_glue_java/ObjectIterator.hpp
  runtime/gc_glue_java/ObjectModel.cpp
  runtime/gc_glue_java/ObjectModel.hpp
  runtime/gc_glue_java/ScavengerDelegate.cpp
  runtime/gc_glue_java/ScavengerDelegate.hpp
  runtime/gc_include/HeapIteratorAPI.h
  runtime/gc_include/j9modron.h
  runtime/gc_realtime/RealtimeAccessBarrier.cpp
  runtime/gc_structs/VMThreadStackSlotIterator.cpp
  runtime/gc_structs/VMThreadStackSlotIterator.hpp
  runtime/gc_trace_vlhgc/TgcInterRegionReferences.cpp
  runtime/gc_vlhgc/CopyForwardScheme.cpp
  runtime/gc_vlhgc/CopyForwardScheme.hpp
  runtime/gc_vlhgc/GlobalMarkCardScrubber.cpp
  runtime/gc_vlhgc/GlobalMarkCardScrubber.hpp
  runtime/gc_vlhgc/GlobalMarkingScheme.cpp
  runtime/gc_vlhgc/GlobalMarkingScheme.hpp
  runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
  runtime/gc_vlhgc/WriteOnceCompactor.cpp
  runtime/gc_vlhgc/WriteOnceCompactor.hpp
  runtime/jvmti/jvmtiHeap.c
  runtime/jvmti/jvmtiHeap10.c
  runtime/oti/VMHelpers.hpp
  runtime/oti/j9javaaccessflags.h
  runtime/vm/createramclass.cpp
  runtime/vm/intfunc.c
Labels: comp:vm, comp:gc, comp:jit, project:loom

#15789 Add ability to sleep before checkpoint
  runtime/compiler/control/CompilationThread.cpp
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/control/J9Options.hpp
Labels: comp:jit, criu

#15828 Add java.specification.maintenance.version=4 jdk8 system property
  runtime/vm/vmprops.c
Labels: jdk8, comp:vm

#15829 Update zlib to fix CVE-2022-37434
  runtime/zlib/inflate.c
Labels: comp:vm

#15841 Add CRIURestoreNonPortableMode test for criu_keepCheckpoint
  test/functional/cmdLineTests/criu/criu_keepCheckpoint.xml
  test/functional/cmdLineTests/criu/playlist.xml
Labels: comp:test

#15834 (0.35) Update zlib to fix CVE-2022-37434
  runtime/zlib/inflate.c
Labels: comp:vm

#15842 JDK19+ j9classshape outputs eetop instead of threadRef
  test/functional/DDR_Test/build.xml
  test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
Labels: comp:test, project:loom

#15823 Add standalone JIT option -XX:[+|-]PerfTool
  runtime/compiler/control/DLLMain.cpp
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/control/J9Options.hpp
  runtime/compiler/control/rossa.cpp
Labels: comp:jit, depends:doc

#15788 Update jvmtiGetStackTrace to support virtual thread
  runtime/jvmti/jvmtiHelpers.c
  runtime/jvmti/jvmtiStackFrame.c
Labels: comp:vm, project:loom, jdk19

#15845 AArch64: Inline Math.fma
  runtime/compiler/aarch64/codegen/J9CodeGenerator.cpp
  runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Labels: comp:jit, arch:aarch64

#15773 Loom: GC Scan Continuation Object -- follow-up change
  runtime/gc_glue_java/ScavengerDelegate.cpp
  runtime/gc_glue_java/ScavengerDelegate.hpp
Labels: comp:gc, project:loom

#15822 zTPF: Add VM z/TPF OS exit hook
  runtime/vm/jniinv.c
  runtime/vm/jvminit.c
Labels: comp:vm, os:ztpf

#15871 Fix doPrivilegedWithCombiner(action) context for domainCombiner access
  jcl/src/java.base/share/classes/java/security/AccessController.java
  test/functional/Java8andUp/src/org/openj9/test/java/security/Test_AccessController.java
Labels: comp:vm

#15811 Update jvmtiGetThreadState() to handle virtual thread
  runtime/jvmti/jvmtiHelpers.c
  runtime/jvmti/jvmtiThread.c
  runtime/jvmti/jvmti_internal.h
  runtime/oti/jvmtiInternal.h
  test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
Labels: comp:vm, project:loom, jdk19

#15744 FFI upcall thunk generation for AArch64
  runtime/vm/xr64/UpcallThunkGen.cpp
Labels: arch:aarch64

#15866 Process Q type in signature
  runtime/codert_vm/thunkcrt.c
Labels: project:valhalla

#15872 Fix stackwalk related jvmti functions
  runtime/jvmti/jvmtiHelpers.c
  runtime/jvmti/jvmtiStackFrame.c
  runtime/jvmti/jvmti_internal.h
  runtime/oti/VMHelpers.hpp
  runtime/oti/j9nonbuilder.h
  runtime/oti/vm_api.h
  runtime/vm/ContinuationHelpers.cpp
Labels: project:loom

#15883 Remove unwanted addition to superset-constants.dat
  debugtools/DDR_VM/data/superset-constants.dat
Labels: comp:vm

#15886 Fix UMA build errors
  runtime/j9vm/j9vmnatives.xml
  runtime/j9vm/module.xml
  runtime/jcl/uma/java_lang_invoke_MethodHandleNatives_exports.xml
  runtime/jcl/uma/se19_exports.xml
Labels: comp:vm

#15891 Readd getConstantPool() method to Class.java
  jcl/src/java.base/share/classes/java/lang/Class.java
Labels: comp:vm

#15775 Limit JITServer AOT cache memory usage
  runtime/compiler/codegen/J9AheadOfTimeCompile.cpp
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/control/JITServerCompilationThread.cpp
  runtime/compiler/env/J9SharedCache.cpp
  runtime/compiler/runtime/JITClientSession.cpp
  runtime/compiler/runtime/JITClientSession.hpp
  runtime/compiler/runtime/JITServerAOTCache.cpp
  runtime/compiler/runtime/JITServerAOTCache.hpp
Labels: comp:jitserver

#15896 Add missing parentheses in macro definitions
  runtime/include/jvmti.h.m4
Labels: comp:vm

#15895 (v0.35.0) Readd getConstantPool() method to Class.java
  jcl/src/java.base/share/classes/java/lang/Class.java
Labels: comp:vm

#15876 Add Continuation cleanup API
  jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
  runtime/j9vm/javanextvmi.cpp
  runtime/oti/VMHelpers.hpp
  runtime/oti/j9nonbuilder.h
  runtime/oti/vm_api.h
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/ContinuationHelpers.cpp
  runtime/vm/bindnatv.cpp
  runtime/vm/intfunc.c
Labels: project:loom

#15870 Check whether array index variable is an induction variable
  runtime/compiler/optimizer/IdiomRecognition.cpp
Labels: comp:jit

#15837 Reinitialize target process info on restore in nonportable mode
  runtime/compiler/control/HookedByTheJit.cpp
Labels: comp:jit, depends:omr, criu

#15894 Increase the size of the header buffer for the !snapformat command
  debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/commands/TraceFileHeaderWriter.java
Labels: comp:vm

#15893 Add copyFieldsFromContinuation helper to internalVMFunctions
  runtime/oti/j9nonbuilder.h
  runtime/oti/vm_api.h
  runtime/vm/ContinuationHelpers.cpp
  runtime/vm/intfunc.c
Labels: project:loom

#15904 (0.35) Check whether array index variable is an induction variable
  runtime/compiler/optimizer/IdiomRecognition.cpp
Labels: comp:jit

#15890 Print full exception details if a jdmpview !-command throws an exception
  debugtools/DDR_VM/src/com/ibm/j9ddr/tools/ddrinteractive/Context.java
Labels: comp:vm

#15909 Change method to look for in testFindstackvalue
  test/functional/DDR_Test/src/j9vm/test/ddrext/Constants.java
  test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestDDRExtensionGeneral.java
  test/functional/DDR_Test/src/j9vm/test/ddrext/junit/TestFindExt.java
  test/functional/DDR_Test/src/j9vm/test/ddrext/util/parser/MethodForNameOutputParser.java
Labels: comp:test

#15873 Add zOS UpcallThunkGen function stubs
  runtime/vm/CMakeLists.txt
  runtime/vm/mz64/UpcallThunkGen.cpp
Labels: comp:vm

#15907 AArch64 macOS: Re-acquire execution permission in compilation threads
  runtime/compiler/control/CompilationThread.cpp
Labels: comp:jit, arch:aarch64, os:macos

#14740 Rebalance Eden after Global GC
  runtime/gc_vlhgc/IncrementalGenerationalGC.cpp
  runtime/gc_vlhgc/SchedulingDelegate.cpp
  runtime/gc_vlhgc/SchedulingDelegate.hpp
Labels: comp:gc

#15774 Continuation Scan Update for generational GC or concurrent GC
  runtime/gc/gctable.c
  runtime/gc_base/gc_internal.h
  runtime/gc_base/modronapi.cpp
  runtime/gc_base/modronapi.hpp
  runtime/oti/j9nonbuilder.h
  runtime/oti/vmconstantpool.xml
  runtime/vm/BytecodeInterpreter.hpp
Labels: comp:gc, project:loom

#15924 (0.35.0) AArch64 macOS: Re-acquire execution permission in compilation threads
  runtime/compiler/control/CompilationThread.cpp
Labels: comp:jit, arch:aarch64, os:macos

#15931 Fix indentation in JIT SignalHandler.c
  runtime/compiler/runtime/SignalHandler.c
Labels: comp:jit

#15846 Add support for VirtualThread getStackTrace
  jcl/src/java.base/share/classes/java/lang/StackWalker.java
  jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
  runtime/jcl/common/java_lang_StackWalker.cpp
  runtime/jcl/common/jclglob.h
  runtime/jcl/common/thread.cpp
  runtime/jcl/exports.cmake
  runtime/jcl/uma/se19_exports.xml
  runtime/oti/vm_api.h
  test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
Labels: project:loom

#15827 Update jvmtiGetThreadListStackTraces to support virtual threads
  runtime/jvmti/jvmtiStackFrame.c
Labels: project:loom

#15914 Loom: Update JVMTI monitor functions
  runtime/jvmti/jvmtiHelpers.c
  runtime/jvmti/jvmtiThread.c
  runtime/jvmti/jvmti_internal.h
Labels: project:loom

#15658 Handle masked operations in VectorAPIExpansion
  runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
  runtime/compiler/env/j9method.cpp
  runtime/compiler/il/J9DataTypes.cpp
  runtime/compiler/optimizer/VectorAPIExpansion.cpp
  runtime/compiler/optimizer/VectorAPIExpansion.hpp
Labels: comp:jit

#15857 Update jvmtiGetOrSetLocal and jvmtiNotifyFramePop to support virtual threads
  runtime/jvmti/jvmtiLocalVariable.c
  runtime/jvmti/jvmtiStackFrame.c
Labels: project:loom

#15955 Correct help message for PointerGenerator
  debugtools/DDR_VM/src/com/ibm/j9ddr/tools/PointerGenerator.java
Labels: comp:vm

#15932 CRIU skips j9sysinfo_get_username/getpwuid to avoid checkpoint failure
  runtime/jcl/common/system.c
  runtime/jcl/unix/syshelp.c
  runtime/oti/j9port_generated.h
  runtime/port/common/j9prt.tdf
  runtime/port/sysvipc/j9sharedhelper.c
  runtime/port/sysvipc/j9shmem.c
  runtime/vm/CRIUHelpers.cpp
  runtime/vm/jvminit.c
Labels: comp:vm, criu

#15552 x64 JIT support for virtual threads (Loom)
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/env/VMJ9.cpp
  runtime/compiler/env/VMJ9.h
  runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp
  runtime/compiler/x/codegen/J9TreeEvaluator.cpp
  runtime/compiler/x/codegen/J9TreeEvaluator.hpp
  runtime/compiler/x/runtime/X86LockReservation.nasm
  runtime/jilgen/jilconsts.c
Labels: comp:jit, project:loom

#15951 Add isVMInStartupPhase() overload taking compilation object
  runtime/compiler/env/J9VMEnv.cpp
  runtime/compiler/env/J9VMEnv.hpp
Labels: comp:jit

#15965 Fix virtualThreadInspectorCount check
  runtime/j9vm/javanextvmi.cpp
Labels: project:loom

#15964 Add java dump end date and approximate duration
  runtime/rasdump/javadump.cpp
Labels: comp:vm, userRaised

#15963 JDK20 deprecates java.lang.Thread.stop()
  runtime/j9vm/exports.cmake
  runtime/j9vm/j7vmi.c
  runtime/j9vm/j9vmnatives.xml
  runtime/jcl/common/thread.cpp
  runtime/jcl/exports.cmake
  runtime/jcl/uma/se6_vm-side_natives_exports.xml
  runtime/oti/jclprots.h
  runtime/oti/vmconstantpool.xml
  runtime/redirector/forwarders.m4
  runtime/vm/vmthread.cpp
Labels: comp:vm, jdk20

#15970 Fix JDK19 java.lang.ref.Reference signature
  jcl/src/java.base/share/classes/java/lang/ref/PhantomReference.java
  jcl/src/java.base/share/classes/java/lang/ref/Reference.java
  jcl/src/java.base/share/classes/java/lang/ref/SoftReference.java
  jcl/src/java.base/share/classes/java/lang/ref/WeakReference.java
Labels: comp:vm, jdk19

#15979 Add missing bounds check to deleteCharAt
  jcl/src/java.base/share/classes/java/lang/StringBuffer.java
  jcl/src/java.base/share/classes/java/lang/StringBuilder.java
  test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuffer.java
  test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_StringBuilder.java
Labels: jdk8, comp:vm

#15969 Fix setEventNotificationMode for unmounted virtual threads
  runtime/jvmti/jvmtiHelpers.c
Labels: project:loom

#15927 Fix StartContinuationProcessing and verbosegc report issues
  runtime/gc_glue_java/ScavengerDelegate.cpp
  runtime/gc_glue_java/ScavengerDelegate.hpp
  runtime/gc_glue_java/ScavengerRootScanner.cpp
  runtime/gc_glue_java/ScavengerRootScanner.hpp
  runtime/gc_stats/CopyForwardStats.hpp
Labels: comp:gc, project:loom

#15968 Update getVirtualThreadState to handle all mounted scenarios
  runtime/jvmti/jvmtiHelpers.c
Labels: comp:vm, project:loom

#15612 Loom: GC Thread scanning
  runtime/gc_base/RootScanner.cpp
  runtime/gc_glue_java/ConcurrentMarkingDelegate.cpp
  runtime/gc_structs/VMThreadStackSlotIterator.cpp
  runtime/gc_structs/VMThreadStackSlotIterator.hpp
Labels: comp:gc, project:loom

#16004 Include JDK17 in OMR coordinated merge documentation
  doc/GuideForCommitters.md
Labels: comp:doc

#16005 JDK20 deprecates java.lang.Thread.suspend() & resume()
  runtime/j9vm/exports.cmake
  runtime/j9vm/j7vmi.c
  runtime/j9vm/j9vmnatives.xml
  runtime/jcl/common/thread.cpp
  runtime/jcl/exports.cmake
  runtime/jcl/uma/se6_vm-side_natives_exports.xml
  runtime/oti/jclprots.h
  runtime/redirector/forwarders.m4
Labels: comp:vm, jdk20

#16007 Support JNI_VERSION_20 for jdk20+
  runtime/include/jni.h.m4
  runtime/j9vm/j7vmi.c
  runtime/j9vm/jvm.c
  runtime/redirector/redirector.c
  runtime/vm/jniinv.c
  runtime/vm/jnimisc.cpp
  runtime/vm/jvminitcommon.c
Labels: comp:vm

#15999 Revert "Preserve ymm/zmm registers on x"
  runtime/codert_vm/xnathelp.m4
  runtime/jilgen/jilconsts.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/xhelpers.m4
Labels: comp:vm, arch:x86

#16013 (0.35.0) Revert "Preserve ymm/zmm registers on x"
  runtime/codert_vm/xnathelp.m4
  runtime/jilgen/jilconsts.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/xhelpers.m4
Labels: comp:vm, arch:x86

#16015 Add stub implementation of JVM_VirtualThreadHideFrames()
  runtime/j9vm/exports.cmake
  runtime/j9vm/j9vmnatives.xml
  runtime/j9vm/javanextvmi.cpp
  runtime/redirector/forwarders.m4
  runtime/redirector/module.xml
Labels: comp:vm, jdk20

#16018 Add BCT_JavaMajorVersionUnshifted()
  runtime/bcutil/ROMClassBuilder.cpp
  runtime/bcutil/defineclass.c
  runtime/j9vm/javanextvmi.cpp
  runtime/oti/j9nonbuilder.h
Labels: comp:vm

#13637 Add Eclipse suggested CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: comp:doc

#16002 x64 JIT support for virtual threads (Loom)
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/env/VMJ9.cpp
  runtime/compiler/env/VMJ9.h
  runtime/compiler/x/amd64/codegen/AMD64JNILinkage.cpp
  runtime/compiler/x/codegen/J9TreeEvaluator.cpp
  runtime/compiler/x/runtime/X86LockReservation.nasm
  runtime/jilgen/jilconsts.c
Labels: comp:jit

#16019 Add JVM_IsValhallaEnabled() for Valhalla builds
  runtime/j9vm/exports.cmake
  runtime/j9vm/j9vmnatives.xml
  runtime/j9vm/javanextvmi.cpp
  runtime/redirector/forwarders.m4
Labels: comp:vm, project:valhalla

#15947 Prepare to use perform() API for TR_Liveness analysis
  runtime/compiler/optimizer/LiveVariablesForGC.cpp
Labels: comp:jit

#15923 Stop sharing TR_VirtualGuard between multiple guards with the same BCI
  runtime/compiler/env/CHTable.cpp
  runtime/compiler/env/CHTable.hpp
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
  runtime/compiler/optimizer/OSRGuardInsertion.cpp
  runtime/compiler/optimizer/OSRGuardRemoval.cpp
Labels: comp:jit, depends:omr:breaking

#15928 Fix caller of getGuaranteedNurseryRange() and use new functions
  runtime/gc_api/GuaranteedNurseryRange.cpp
  runtime/gc_base/GenerationalAccessBarrierComponent.cpp
  runtime/gc_modron_standard/StandardAccessBarrier.cpp
  runtime/gcchk/gcchk.cpp
Labels: comp:gc, depends:omr
