Repository eclipse-openj9/openj9, pull requests merged in 2023-05, with the labels that each got.

#17187 Add Unsupported Warning for Hierarchical Scan Ordering with Balanced
  runtime/gc_vlhgc/ConfigurationIncrementalGenerational.cpp
  runtime/nls/j9gc/j9modron.nls
Labels: comp:gc

#17335 Revert "Fix to handle suspend/resume of virtual/carrier threads"
  runtime/j9vm/javanextvmi.cpp
  runtime/jcl/common/jclcinit.c
  runtime/jcl/common/thread.cpp
  runtime/jvmti/jvmtiHelpers.c
  runtime/jvmti/jvmtiThread.c
  runtime/jvmti/suspendhelper.cpp
  runtime/oti/j9nonbuilder.h
Labels: comp:vm

#17317 Stop failing compilations due to final Object invokeinterface
  runtime/compiler/compile/J9SymbolReferenceTable.cpp
Labels: comp:jit

#17236 Don't differenciate Q from L types in verifier
  runtime/bcverify/rtverify.c
  runtime/bcverify/vrfyhelp.c
  runtime/oti/bytecodewalk.h
  runtime/oti/cfreader.h
  runtime/verbose/errormessageframeworkrtv.c
  runtime/verbose/errormessagehelper.c
Labels: comp:vm, project:valhalla

#17342 Remove unwanted, misleading comment
  runtime/oti/j9consts.h
Labels: comp:vm

#17346 Update OMR Acceptance build documentation for coordinated merges
  doc/GuideForCommitters.md
Labels: comp:doc

#17345 Remove JAVA19 pConfig & JAVA21 uses rt-compressed.sunJava21.jar
  jcl/jpp_configuration.xml
Labels: comp:vm

#13619 Allow inlining of java/lang/ref/Reference.refersTo method
  runtime/compiler/codegen/J9RecognizedMethodsEnum.hpp
  runtime/compiler/compile/J9Compilation.cpp
  runtime/compiler/compile/J9Compilation.hpp
  runtime/compiler/control/JITClientCompilationThread.cpp
  runtime/compiler/env/VMJ9.cpp
  runtime/compiler/env/VMJ9.h
  runtime/compiler/env/VMJ9Server.cpp
  runtime/compiler/env/VMJ9Server.hpp
  runtime/compiler/env/j9method.cpp
  runtime/compiler/runtime/JITClientSession.hpp
Labels: comp:jit, perf

#17331 Hoist getSupportsInlineStringHashCode check for better readability
  runtime/compiler/x/codegen/J9TreeEvaluator.cpp
Labels: comp:jit

#17338 Use a recent OMR acceptance build as bootjdk for AIX and for s390x Linux
  buildenv/jenkins/variables/defaults.yml
Labels: comp:build

#17313 Make JITServer CRIU tests more robust
  test/functional/cmdLineTests/criu/criuJitServerScript.sh
  test/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml
  test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml
  test/functional/cmdLineTests/criu/playlist.xml
  test/functional/cmdLineTests/criu/src/org/openj9/criu/OptionsFileTest.java
  test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml
  test/functional/cmdLineTests/jitserver/jitserverScript.sh
Labels: comp:test, comp:jitserver, criu

#17310 Set CurrentThread sym ref in defaultMethodDefAliases
  runtime/compiler/compile/J9AliasBuilder.cpp
  runtime/compiler/compile/J9SymbolReferenceTable.cpp
Labels: comp:jit

#17370 Correct condition for preparing offloading library
  runtime/vm/jvminit.c
Labels: comp:vm

#17306 Support offloading for jdk17+
  runtime/j9vm/exports.cmake
  runtime/j9vm/j7vmi.c
  runtime/j9vm/j9scar.tdf
  runtime/j9vm/j9vmnatives.xml
  runtime/j9vm/jvm.c
  runtime/jvmti/jvmtiStartup.c
  runtime/oti/j9consts.h
  runtime/oti/util_api.h
  runtime/redirector/forwarders.m4
  runtime/util/util.tdf
  runtime/vm/bindnatv.cpp
  runtime/vm/vmbootlib.c
Labels: comp:vm

#17379 Remove obsolete references to freetype in jdk8 build instructions
  doc/build-instructions/Build_Instructions_V8.md
Labels: comp:doc

#17330 Refactor GC Object List Allocation/Initialization
  runtime/gc_glue_java/ConfigurationDelegate.hpp
Labels: comp:gc, criu

#17380 Throw UnsupportedOperationException in sun.misc.Perf.attach natives
  runtime/jcl/common/sun_misc_Perf.c
Labels: comp:vm

#17374 Provide a better error message for failed library loads on jdk17+
  runtime/j9vm/jvm.c
Labels: comp:vm

#17381 Add missing value type check before zero the lockword
  runtime/gc_include/ObjectAccessBarrierAPI.hpp
Labels: comp:vm, comp:gc, project:valhalla

#17391 Return false from JVM_DTraceIsSupported
  runtime/j9vm/j7vmi.c
  runtime/redirector/forwarders.m4
Labels: comp:vm

#17278 DDR: Fix function call parsing in StackMap
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackmap/StackMap.java
Labels: comp:vm

#17344 Prototype Continuation caching
  runtime/gc_base/GCExtensions.cpp
  runtime/jcl/common/stdinit.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/vm_api.h
  runtime/vm/ContinuationHelpers.cpp
  runtime/vm/intfunc.c
  runtime/vm/jvmfree.c
  runtime/vm/jvminit.c
Labels: comp:vm, perf, project:loom

#17403 Fix handling of IPv6 addressed
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/view/dtfj/J9RASInfoBootstrapShim.java
Labels: comp:vm

#17101 Sync JVM init and exit paths
  runtime/vm/jniinv.c
  runtime/vm/jvminit.c
Labels: comp:vm

#17375 Teach ValueTypeUnsafeTests about dual header shape
  test/functional/Valhalla/src/org/openj9/test/lworld/ValueTypeUnsafeTests.java
Labels: comp:test

#17369 Add 31-64 interop support for JVM_ funcs for JDK17+
  runtime/j9vm/exports.cmake
  runtime/j9vm/j7vmi.c
  runtime/j9vm/j9scar.tdf
  runtime/j9vm/j9vmnatives.xml
  runtime/j9vm/jvm.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/vm_api.h
  runtime/redirector/forwarders.m4
  runtime/vm/intfunc.c
  runtime/vm/vmbootlib.c
Labels: comp:vm

#16854 Add new optimization catchBlockProfiler
  runtime/compiler/build/files/common.mk
  runtime/compiler/control/CompilationThread.cpp
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/control/J9Options.hpp
  runtime/compiler/control/J9Recompilation.cpp
  runtime/compiler/env/VMJ9.cpp
  runtime/compiler/ilgen/IlGenerator.cpp
  runtime/compiler/optimizer/CMakeLists.txt
  runtime/compiler/optimizer/CatchBlockProfiler.cpp
  runtime/compiler/optimizer/CatchBlockProfiler.hpp
  runtime/compiler/optimizer/EstimateCodeSize.cpp
  runtime/compiler/optimizer/EstimateCodeSize.hpp
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
  runtime/compiler/optimizer/J9EstimateCodeSize.cpp
  runtime/compiler/optimizer/J9Optimizer.cpp
  runtime/compiler/runtime/J9Profiler.cpp
  runtime/compiler/runtime/J9Profiler.hpp
Labels: comp:jit, depends:omr

#17408 [Jtreg/FFI] Remove the null segment check for pointer
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java
  runtime/tests/clinkerffi/CMakeLists.txt
  runtime/tests/clinkerffi/downcall.c
  runtime/tests/clinkerffi/module.xml
  runtime/tests/clinkerffi/upcall.c
  test/functional/Java17andUp/src_170/org/openj9/test/jep389/downcall/InvalidDownCallTests.java
  test/functional/Java17andUp/src_170/org/openj9/test/jep389/upcall/InvalidUpCallTests.java
  test/functional/Java20andUp/src/org/openj9/test/jep434/downcall/InvalidDownCallTests.java
  test/functional/Java20andUp/src/org/openj9/test/jep434/upcall/InvalidUpCallTests.java
  test/functional/Java21andUp/src/org/openj9/test/jep442/downcall/InvalidDownCallTests.java
  test/functional/Java21andUp/src/org/openj9/test/jep442/upcall/InvalidUpCallTests.java
Labels: comp:vm, project:panama, jdk17, jdk20

#17413 Add areFlattenableValueTypesEnabled() for JIT
  runtime/oti/j9nonbuilder.h
  runtime/oti/vm_api.h
  runtime/vm/ValueTypeHelpers.cpp
  runtime/vm/intfunc.c
Labels: comp:vm, comp:jit, project:valhalla

#17048 Correctly handle primitive VTs in System.arraycopy
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/ValueTypeHelpers.hpp
Labels: comp:vm, project:valhalla

#17434 Fix compile error due to unused variable
  runtime/vm/ValueTypeHelpers.hpp
Labels: comp:vm

#17436 Fix bug related to J9::Options::_compilationDelayTime unit
  runtime/compiler/control/HookedByTheJit.cpp
Labels: comp:jit

#17406 Simplify callMustBeInlinedRegardlessOfSize calls
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
Labels: comp:jit

#17260 Add CH Table AOT Feature Flag
  runtime/compiler/runtime/RelocationRuntime.cpp
  runtime/compiler/runtime/RelocationRuntime.hpp
  runtime/nls/jitm/j9jit.nls
Labels: bug, comp:jit, comp:jit:aot

#17448 CRIU restore clears InetAddress.cache
  jcl/src/java.base/share/classes/module-info.java.extra
  jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
Labels: comp:vm, criu

#17425 Handle code cache alloction for low memory
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/control/J9Options.hpp
  runtime/compiler/control/OptionsPostRestore.cpp
  runtime/compiler/control/rossa.cpp
  runtime/nls/jitm/j9jit.nls
Labels: comp:jit

#17453 Adding helper functions for crc32 special routines to enable optimizations in AOT
  runtime/compiler/p/codegen/PPCJNILinkage.cpp
  runtime/compiler/runtime/Runtime.cpp
Labels: comp:jit, depends:omr, blocker, arch:power

#17327 Set symbol declared class for field shadows
  runtime/compiler/compile/J9SymbolReferenceTable.cpp
Labels: comp:jit, depends:omr

#17073 Add support for persistent SCC on z/OS
  buildspecs/j9.flags
  buildspecs/zos_390-64.spec
  buildspecs/zos_390-64_cmprssptrs.spec
  buildspecs/zos_390.spec
  runtime/bcutil/jimagereader.c
  runtime/cmake/caches/zos_390-64.cmake
  runtime/cmake/options.cmake
  runtime/include/j9cfg.h.in
  runtime/nls/shrc/j9shr.nls
  runtime/oti/j9port.h
  runtime/oti/shcflags.h
  runtime/oti/util_api.h
  runtime/shared_common/CompositeCache.cpp
  runtime/shared_common/CompositeCacheImpl.hpp
  runtime/shared_common/OSCache.cpp
  runtime/shared_common/OSCache.hpp
  runtime/shared_common/OSCachemmap.cpp
  runtime/shared_common/OSCachemmap.hpp
  runtime/shared_common/OSCachesysv.cpp
  runtime/shared_common/OSCachesysv.hpp
  runtime/shared_common/j9shr.tdf
  runtime/shared_common/shrinit.cpp
  runtime/shared_common/shrinit.h
  runtime/tests/port/j9mmapTest.c
  runtime/tests/shared/AttachedDataTest.cpp
  runtime/util/zos/freessp.c
  test/functional/cmdLineTests/shareClassTests/SCCMLTests/ShareClassesCMLTests-1.xml
Labels: comp:vm, depends:omr, os:zos

#17470 Add/update java.specification.maintenance.version
  runtime/vm/vmprops.c
Labels: comp:vm

#17352 Disable FFI specific code for compilation in JDK21
  jcl/src/java.base/share/classes/jdk/internal/foreign/abi/DowncallLinker.java
  jcl/src/java.base/share/classes/jdk/internal/foreign/abi/UpcallLinker.java
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java
  jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableInvoker.java
  jcl/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/abi/ProgrammableUpcallHandler.java
  jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
  jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java
  jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/LayoutStrPreprocessor.java
  jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/TypeLayoutCheckHelper.java
  jcl/src/jdk.incubator.foreign/share/classes/openj9/internal/foreign/abi/UpcallMHMetaData.java
  runtime/j9vm/exports.cmake
  runtime/j9vm/j9vmnatives.xml
  runtime/j9vm/javanextvmi.cpp
  runtime/oti/vmconstantpool.xml
  runtime/redirector/forwarders.m4
  runtime/vm/OutOfLineINL_openj9_internal_foreign_abi_UpCallMHMetaData.cpp
  runtime/vm/UpcallVMHelpers.cpp
  test/functional/Java19andUp/build.xml
  test/functional/Java21andUp/build.xml
Labels: project:panama, jdk21

#17468 Update openssl to version 1.1.1u
  buildenv/jenkins/variables/defaults.yml
Labels: comp:openssl

#17475 Call static method VM.getVMArgs() from JNI as a static method
  runtime/j9vm/java11vmi.c
Labels: comp:vm

#17461 Rework RegionExtenstion/Object List Initialization
  runtime/gc_base/ContinuationObjectList.cpp
  runtime/gc_base/ContinuationObjectList.hpp
  runtime/gc_base/OwnableSynchronizerObjectList.cpp
  runtime/gc_base/OwnableSynchronizerObjectList.hpp
  runtime/gc_base/ReferenceObjectList.cpp
  runtime/gc_base/ReferenceObjectList.hpp
  runtime/gc_base/UnfinalizedObjectList.cpp
  runtime/gc_base/UnfinalizedObjectList.hpp
  runtime/gc_glue_java/ConfigurationDelegate.hpp
  runtime/gc_glue_java/HeapRegionDescriptorStandardExtension.hpp
Labels: comp:gc

#17494 Correct SPDX license identifiers
  test/functional/cmdLineTests/criu/src/org/openj9/criu/TestResult.java
Labels: comp:test, criu
