Repository eclipse-openj9/openj9, pull requests merged in 2023-04, with the labels that each got.

#17015 AArch64: Enable arrayset optimizations
  runtime/compiler/control/J9Options.cpp
Labels: comp:jit, arch:aarch64

#17081 Relocate state of Continuation from native structure to Object
  jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
  runtime/gc_base/GCExtensions.cpp
  runtime/oti/VMHelpers.hpp
  runtime/oti/j9nonbuilder.h
  runtime/oti/vmconstantpool.xml
  runtime/vm/ContinuationHelpers.cpp
Labels: comp:vm, comp:gc, project:loom

#17110 zOS AttachAPI doesn't use FileLockWatchdogTask for CommonControlFiles
  jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/CommonDirectory.java
  jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/FileLock.java
  jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/IPC.java
  jcl/src/java.base/share/classes/openj9/internal/tools/attach/target/WaitLoop.java
  jcl/src/jdk.attach/share/classes/com/ibm/tools/attach/attacher/OpenJ9VirtualMachine.java
  test/functional/Java8andUp/src/org/openj9/test/fileLock/NativeFileLock.java
Labels: comp:vm

#17106 Update GC DDR to Remove Unused GC MemoryPoolHybrid
  runtime/ddr/gcddr.cpp
Labels: comp:gc

#17100 AArch64: Save return address in VMThread in NEW_DUAL_MODE_HELPER
  runtime/codert_vm/arm64nathelp.m4
Labels: comp:jit, arch:aarch64

#17118 valhalla enable java/lang/Access methods
  jcl/src/java.base/share/classes/java/lang/Access.java
Labels: comp:vm, project:valhalla, jdk21

#17004 Handling of non-TLS client connect failures to an encrypted JITServer
  runtime/compiler/control/CompilationThread.cpp
  runtime/compiler/control/JITServerHelpers.cpp
  runtime/compiler/net/CommunicationStream.cpp
  runtime/compiler/net/CommunicationStream.hpp
Labels: comp:jitserver

#17130 Provide JITServer implementation for CRIU specific FE queries
  runtime/compiler/control/JITClientCompilationThread.cpp
  runtime/compiler/env/VMJ9.h
  runtime/compiler/env/VMJ9Server.cpp
  runtime/compiler/env/VMJ9Server.hpp
  runtime/compiler/net/CommunicationStream.hpp
  runtime/compiler/net/MessageTypes.cpp
  runtime/compiler/net/MessageTypes.hpp
  runtime/compiler/runtime/JITClientSession.hpp
Labels: comp:jitserver, criu

#17001 Ignore null classes when searching the FCC
  runtime/vm/ValueTypeHelpers.cpp
Labels: comp:vm, project:valhalla

#17136 Read-acquire Class Unload Mutex for compilation before checkpoint
  runtime/compiler/control/CompileBeforeCheckpoint.cpp
Labels: comp:jit, criu

#17143 Remove empty parentheses when constructing TR::ClassUnloadMonitorCriticalSection object
  runtime/compiler/control/CompileBeforeCheckpoint.cpp
Labels: comp:jit, criu

#17148 Clarify usage of the body info address relocations
  doc/compiler/aot/RelocationRecords.md
Labels: comp:doc

#17150 Read-acquire Class Unload Mutex for compilation before checkpoint (0.38)
  runtime/compiler/control/CompileBeforeCheckpoint.cpp
Labels: comp:jit, criu

#17151 Provide JITServer implementation for CRIU specific FE queries (0.38.0)
  runtime/compiler/control/JITClientCompilationThread.cpp
  runtime/compiler/env/VMJ9.h
  runtime/compiler/env/VMJ9Server.cpp
  runtime/compiler/env/VMJ9Server.hpp
  runtime/compiler/net/CommunicationStream.hpp
  runtime/compiler/net/MessageTypes.cpp
  runtime/compiler/net/MessageTypes.hpp
  runtime/compiler/runtime/JITClientSession.hpp
Labels: comp:jitserver, criu

#16974 Add support for -XX:[+|-]HandleSIGUSR2
  runtime/jcl/common/sigusr2.c
  runtime/oti/jvminit.h
  runtime/vm/jvminit.c
Labels: comp:vm

#17149 (0.38) Add support for -XX:[+|-]HandleSIGUSR2
  runtime/jcl/common/sigusr2.c
  runtime/oti/jvminit.h
  runtime/vm/jvminit.c
Labels: comp:vm

#17141 Print warning when java.io.tmpDir does not exist
  jcl/src/java.base/share/classes/java/lang/ClassLoader.java
  jcl/src/java.base/share/classes/java/lang/System.java
  runtime/jcl/common/system.c
Labels: comp:vm

#17154 Minor javadoc fixes
  jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUDumpPermission.java
Labels: comp:doc

#17152 Remove redundant tests of OPENJDK_METHODHANDLES
  jcl/src/java.base/share/classes/java/lang/System.java
Labels: comp:vm

#17127 [FFI/JDK20_Jtreg] Handle CaptureCallState in the downcall handle
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/bindnatv.cpp
Labels: comp:vm, project:panama, jdk20

#17142 [FFI/JDK20_Jtreg] Normalize the arguments in the upcall dispatcher
  runtime/oti/j9nonbuilder.h
  runtime/vm/UpcallVMHelpers.cpp
Labels: comp:vm, project:panama, jdk20

#17126 Never validate class names provided via privileged API for jdk21+
  runtime/jcl/common/clsldr.cpp
Labels: comp:vm

#17147 Create draft 0.38.0 release note
  doc/release-notes/0.38/0.38.md
Labels: comp:doc

#17093 Update !vthread command to use GC continuation list
  debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/VirtualThreadsCommand.java
  runtime/rasdump/trigger.c
Labels: comp:vm

#17161 Update OpenSSL with additional CVE fixes to 1.1.1t
  buildenv/jenkins/variables/defaults.yml
Labels: comp:build, comp:openssl

#17167 DirectByteBuffer accepts long capacity in jdk21+
  runtime/vm/jnicsup.cpp
Labels: comp:vm, jdk21

#17158 Remove unwanted spaces in preprocessor directives
  jcl/src/java.base/share/classes/com/ibm/oti/vm/ORBBase.java
  jcl/src/java.base/share/classes/com/ibm/oti/vm/ORBVMHelpers.java
  jcl/src/java.base/share/classes/java/lang/Class.java
  jcl/src/java.base/share/classes/java/lang/ClassLoader.java
  jcl/src/java.base/share/classes/java/lang/J9VMInternals.java
  jcl/src/java.base/share/classes/java/lang/Object.java
  jcl/src/java.base/share/classes/java/lang/System.java
  jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalUpcallHandler.java
  jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/MemoryMXBeanImpl.java
  jcl/src/java.management/share/classes/java/lang/management/MemoryMXBean.java
  jcl/src/jdk.jcmd/share/classes/openj9/tools/attach/diagnostics/attacher/AttacherDiagnosticsProvider.java
  jcl/src/openj9.criu/share/classes/org/eclipse/openj9/criu/CRIUSupport.java
  jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassHelperFactory.java
  jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassHelperFactoryImpl.java
Labels: comp:vm

#17174 (0.37) Add DDR command !vthreads
  debugtools/DDR_VM/src/com/ibm/j9ddr/AuxFieldInfo29.dat
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9ObjectHelper.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/GetCommandsTask.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/JavaVersionHelper.java
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/VirtualThreadsCommand.java
  runtime/rasdump/trigger.c
Labels: comp:vm, project:loom

#17169 (0.37) Update OpenSSL with additional CVE fixes to 1.1.1t
  buildenv/jenkins/variables/defaults.yml
Labels: comp:build, comp:openssl

#17170 (0.38) Update OpenSSL with additional CVE fixes to 1.1.1t
  buildenv/jenkins/variables/defaults.yml
Labels: comp:build, comp:openssl

#17159 CRIU not set J9_EXTENDED_RUNTIME_DEBUG_MODE and enable DO_HOOKS
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/jvminit.c
Labels: comp:vm, criu

#17132 Fix SCC AOT code validation in checkpoint-mode
  runtime/compiler/control/rossa.cpp
Labels: comp:jit, comp:jit:aot, criu

#17184 Fix cmdLineTests for JVM option setting
  test/functional/cmdLineTests/variables.mk
Labels: comp:test

#17177 (v0.38.0-release) CRIU not set J9_EXTENDED_RUNTIME_DEBUG_MODE and enable DO_HOOKS
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/jvminit.c
Labels: comp:vm, criu

#17178 Update 0.37 release notes, OpenJDK 19 is out of support
  doc/release-notes/0.37/0.37.md
Labels: comp:doc

#17197 Copy the 0.37 release notes to the 0.37 branch
  doc/release-notes/0.37/0.37.md
Labels: comp:doc

#17166 Convert notices to markdown and include CRIU and OpenSSL
  NOTICES.md
  notice.html
Labels: comp:doc

#17194 Increase wait time in test_YieldedVirtualThreadGetStackTrace
  test/functional/Java19andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
  test/functional/Java20andUp/src/org/openj9/test/jep425/VirtualThreadTests.java
Labels: comp:test

#17190 Fix missing concurrent scan finish notification
  runtime/oti/VMHelpers.hpp
  runtime/vm/ContinuationHelpers.cpp
Labels: comp:vm, comp:gc, project:loom

#17191 Avoid timing hole caused by instruction reordering
  runtime/vm/ContinuationHelpers.cpp
Labels: comp:vm, comp:gc, project:loom

#17103 Add checks to prevent invalid address access in MethodMetaData
  runtime/compiler/runtime/MethodMetaData.c
Labels: comp:jit

#16973 Update JIT Hooks Document
  doc/compiler/runtime/JITHooks.md
Labels: comp:jit, comp:doc

#17145 Refactor GC CRIU Routines
  runtime/gc/gctable.c
  runtime/gc_base/gc_internal.h
  runtime/gc_base/modronapi.cpp
  runtime/gc_modron_startup/mminit.cpp
  runtime/gc_realtime/Scheduler.hpp
  runtime/oti/j9nonbuilder.h
Labels: comp:gc, criu

#17182 Check options on whether or not to inline Thread.currentThread
  runtime/compiler/env/VMJ9.cpp
Labels: comp:jit, depends:omr

#17216 Avoid hang in Test_ThreadGroup.test_remove() on jdk21
  test/functional/Java8andUp/src/org/openj9/test/java/lang/Test_ThreadGroup.java
Labels: comp:test, jdk21

#17219 Support JNI_VERSION_21 for jdk21+
  runtime/include/jni.h.m4
  runtime/j9vm/j7vmi.c
  runtime/j9vm/jvm.c
  runtime/redirector/redirector.c
  runtime/vm/jnimisc.cpp
  runtime/vm/jvminitcommon.c
Labels: comp:vm, jdk21

#17221 Ignore ScopedMemoryAccess in isCallerClassJavaNio()
  runtime/vm/gphandle.c
Labels: comp:vm

#17186 jvmti: delay allocation of tls keys
  runtime/jvmti/jvmtiHelpers.c
Labels: comp:vm

#17223 Update 0.38.0 release note
  doc/release-notes/0.38/0.38.md
Labels: comp:doc

#17227 Fully distinguish body info address relocations
  doc/compiler/aot/RelocationRecords.md
Labels: comp:doc

#17157 x86: Preserve xmm4 in fpRem helper
  runtime/compiler/x/runtime/X86Codert.nasm
Labels: comp:jit, arch:x86

#17214 Stop adding -javaagent to classpath
  runtime/vm/jvminit.c
Labels: comp:vm

#17229 Prepare MM_Scheduler for OMR Base Class Changes
  runtime/gc_realtime/Scheduler.cpp
  runtime/gc_realtime/Scheduler.hpp
Labels: comp:gc

#17193 Merge started and finished flags into continuation.state
  jcl/src/java.base/share/classes/jdk/internal/vm/Continuation.java
  runtime/oti/vm_api.h
  runtime/oti/vmconstantpool.xml
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/ContinuationHelpers.cpp
  runtime/vm/bindnatv.cpp
Labels: comp:vm, project:loom

#17200 Fix inlining when the root method is a customized LambdaForm
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
Labels: comp:jit

#17168 Create prex arg info from callee symbol for array-typed parameters
  runtime/compiler/optimizer/InlinerTempForJ9.cpp
Labels: comp:jit

#17201 JDK21 sets bootclassloader.unnamedModule after java.base module creation
  runtime/j9vm/java11vmi.c
  runtime/util/module.tdf
Labels: comp:vm, jdk21

#17237 Stop exporting functions not needed for Java 21
  runtime/j9vm/exports.cmake
  runtime/j9vm/j7vmi.c
  runtime/j9vm/j9vmnatives.xml
  runtime/redirector/forwarders.m4
Labels: comp:vm

#16820 Replace J9VM_MODRON_SCAVENGER_CACHE_* to OMR_COPYSCAN_CACHE_*
  debugtools/DDR_VM/data/superset-constants.dat
  runtime/gc_vlhgc/CopyForwardScheme.cpp
  runtime/gc_vlhgc/CopyScanCacheChunkVLHGCInHeap.cpp
  runtime/gc_vlhgc/CopyScanCacheChunkVLHGCInHeap.hpp
  runtime/gc_vlhgc/CopyScanCacheListVLHGC.cpp
  runtime/gc_vlhgc/CopyScanCacheListVLHGC.hpp
  runtime/gc_vlhgc/CopyScanCacheVLHGC.hpp
Labels: comp:gc, depends:omr

#17259 Add check for string length in getCachedUTFString()
  runtime/shared_common/CacheMap.cpp
  runtime/shared_common/j9shr.tdf
Labels: comp:vm

#17246 Don't reload j9thr from the wrong location
  runtime/j9vm/jvm.c
  runtime/oti/j9nonbuilder.h
  runtime/oti/vm_api.h
  runtime/sunvmi/sunvmi.c
  runtime/vm/jvminit.c
Labels: comp:vm

#17261 (0.38) Add check for string length in getCachedUTFString()
  runtime/shared_common/CacheMap.cpp
  runtime/shared_common/j9shr.tdf
Labels: comp:vm

#17257 Remove private system properties in jdk17+
  jcl/src/java.base/share/classes/java/lang/System.java
Labels: comp:vm

#17264 DDR: Fix NPE in StackMap logging
  debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/j9/stackmap/StackMap.java
Labels: comp:vm

#17087 [FFI/JDK20_Jtreg] Fix the issue with the arguments/return value
  jcl/src/java.base/share/classes/openj9/internal/foreign/abi/InternalDowncallHandler.java
  runtime/vm/UpcallVMHelpers.cpp
Labels: comp:vm, project:panama, jdk20

#17183 Update source/target versions to 8
  test/functional/RasapiTest/build.xml
Labels: comp:test

#17262 Copy functional test excludes for 21 from 20
  test/TestConfig/resources/excludes/latest_exclude_21.txt
Labels: comp:test

#17245 CRIU BytecodeInterpreter enables DO_HOOKS
  runtime/makelib/targets.mk.ftl
  runtime/makelib/targets.mk.linux.inc.ftl
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/CMakeLists.txt
  runtime/vm/CRIUBytecodeInterpreterCompressed.cpp
  runtime/vm/CRIUBytecodeInterpreterFull.cpp
  runtime/vm/jvminit.c
Labels: comp:vm, criu

#17293 (v0.38.0-release) CRIU BytecodeInterpreter enables DO_HOOKS
  runtime/makelib/targets.mk.ftl
  runtime/makelib/targets.mk.linux.inc.ftl
  runtime/vm/BytecodeInterpreter.hpp
  runtime/vm/CMakeLists.txt
  runtime/vm/CRIUBytecodeInterpreterCompressed.cpp
  runtime/vm/CRIUBytecodeInterpreterFull.cpp
  runtime/vm/jvminit.c
Labels: comp:vm, criu

#17192 AArch64: Use stp/ldp instructions for preserved registers
  runtime/compiler/aarch64/codegen/ARM64PrivateLinkage.cpp
Labels: comp:jit, arch:aarch64

#17213 AArch64: Remove a TODO comment for ArrayCopyBNDCHK
  runtime/compiler/aarch64/codegen/J9TreeEvaluator.cpp
Labels: comp:jit, arch:aarch64

#17292 Add unique ID comment to CommunicationStream::MINOR_NUMBER
  runtime/compiler/net/CommunicationStream.hpp
Labels: comp:jitserver

#17276 Make J9::ClassEnv::getArrayElementWidthInBytes() work in JITServer
  runtime/compiler/env/J9ClassEnv.cpp
Labels: comp:jitserver

#17297 CRIU BytecodeInterpreter requires J9VM_OPT_CRIU_SUPPORT
  runtime/vm/CRIUBytecodeInterpreterCompressed.cpp
  runtime/vm/CRIUBytecodeInterpreterFull.cpp
Labels: comp:vm, criu

#17304 Update 0.38.0 release notes
  doc/release-notes/0.38/0.38.md
Labels: comp:doc

#17205 Enable JITServer post-restore only if explicitly specified
  doc/compiler/control/OptionsPostRestore.md
  runtime/compiler/control/CompilationRuntime.hpp
  runtime/compiler/control/CompilationThread.cpp
  runtime/compiler/control/J9Options.cpp
  runtime/compiler/control/OptionsPostRestore.cpp
  test/functional/cmdLineTests/criu/build.xml
  test/functional/cmdLineTests/criu/criuJitServerScript.sh
  test/functional/cmdLineTests/criu/criu_jitserverAcrossCheckpoint.xml
  test/functional/cmdLineTests/criu/criu_jitserverPostRestore.xml
  test/functional/cmdLineTests/criu/playlist.xml
  test/functional/cmdLineTests/jitserver/build.xml
  test/functional/cmdLineTests/jitserver/jitserverArgumentTesting.xml
  test/functional/cmdLineTests/jitserver/jitserverScript.sh
  test/functional/cmdLineTests/jitserver/jitserverconfig.sh
  test/functional/cmdLineTests/jitserver/playlist.xml
Labels: comp:test, comp:jitserver, criu

#17273 GC Scheduler Cleanup
  runtime/gc_realtime/Scheduler.cpp
  runtime/gc_realtime/Scheduler.hpp
Labels: comp:gc
